### PR TITLE
Address migration

### PR DESCRIPTION
**Pull request by StevenMetz**
Made suggested changes, not entirely sure if they will remove token from requests after I have git ignored it

### CODE REVIEW

**Comment by StevenMetz** [comment]
@darbyfrey

**Comment by darbyfrey** [comment]
@StevenMetz, I think you need to `git rm` those files to remove them from git. I think this page explains it okay https://www.git-tower.com/learn/git/commands/git-rm

Don't get hung up on that for now, it's a good practice to get into, but I wouldn't spend too much time on it.

**Comment by darbyfrey** [comment]
Otherwise, the migration looks good 👍

**Comment by StevenMetz** [comment]
Excellent thank you for the feedback!

**Comment by StevenMetz** [comment]
I removed those http request files with the help of your resource thank you!

**Pull request merged**
